### ISSUE TITLE
IMtoken leading zero on price field.

### ISSUE THREAD

**Issue by chrismaree** [carboclan/dapp.honeylemon.market#119]
After loading the `Offer` page and entering a number, the field defaults to having a leading zsero in the quantity. this should be removed.

![image](https://user-images.githubusercontent.com/12886084/84540410-8cf43100-acf5-11ea-8b79-4aca7dab18ec.png)

**Comment by FSM1** [comment]
If you navigate away from the field, the 0 will be removed on focus being lost.

**Comment by FSM1** [comment]
This is also fixed at a more fundamental level in the latest release since
I am now using a placeholder value
