### ISSUE TITLE
Live market stats on IMToken takes a long time to load

### ISSUE THREAD

**Issue by chrismaree** [carboclan/dapp.honeylemon.market#122]
- [x] After going to live market stats I had to wait upwards of 15 seconds before the chart drew on screen. after loading this, navigating to a different page then back to the live stats the graph drew correctly first time. not sure if this can be easily fixed.
- [ ] The sentence ends without a full stop.
- [ ] There should perhaps be a `i` or `?` next to this cloud mining contrast to explain where these numbers come from and what they mean. This is a bit confusing. @CarboClanC you can put content in here.

![IMAGE 2020-06-12 21:59:05](https://user-images.githubusercontent.com/12886084/84541553-ef4e3100-acf7-11ea-903f-82283fb68547.jpg)

**Comment by FSM1** [comment]
@chrismaree Happy if I close this with the updated stats page?

**Comment by FSM1** [comment]
this is resolved in #125
