### ISSUE TITLE
Menu should highlight what page I'm currently on

### ISSUE THREAD

**Issue by chrismaree** [carboclan/dapp.honeylemon.market#124]
In this screenshot im on the offer tab. however, the menu does not indicate this. it would be nice for this to be a shade of gray perhaps to indicate the page the user is on.

![image](https://user-images.githubusercontent.com/12886084/85075308-3d62a900-b1be-11ea-813c-149bd73b6dd2.png)

**Comment by FSM1** [comment]
This is resolved in #125
