### ISSUE TITLE
Favicon is hard to see

### ISSUE THREAD

**Issue by chrismaree** [carboclan/dapp.honeylemon.market#158]
The favicon has a lot of white in it that makes it hard to see.

![image](https://user-images.githubusercontent.com/12886084/85921203-ea9e8680-b87a-11ea-8acd-9b6a53281b33.png)

This should be replaced with a black logo, like this one in the menu bar

![image](https://user-images.githubusercontent.com/12886084/85921210-f4c08500-b87a-11ea-803e-d33e2d59fb2f.png)

**Comment by FSM1** [comment]
looks fine here: 
![image](https://user-images.githubusercontent.com/12774278/85933592-118ba580-b8d9-11ea-9ba9-af9d3bfdb714.png)

**Comment by FSM1** [comment]
closed in #181
