### ISSUE TITLE
Main net 2 day contract testing

### ISSUE THREAD

**Issue by chrismaree** [carboclan/dapp.honeylemon.market#185]
This issue outlines the testing on the 2 day contract. The exact txs, setup and values at each step are outlined.

# Wallet 1: miner - IMToken _with DSProxy_
- Address: 0x2F20a61E5f3c379475C6b6b6d38B61AdAD1Eca25
- Sell Order1 (subsequently canceled to test cancellation logic).
	- Price: 0.075
	- Quantity: 500
- Sell Order2:
	- Price: 0.074
	- Quantity: 100
- Sell Order3:
	- Price: 0.073
	- Quantity: 100
- Sell Order4: 
	- Price 0.075
 	-Quantity: 300

### Steps in flow:
**1. Buy Imbtc with Ether.**
This was pretty easy using the built-in Tokenlon exchange.

**2. create sell offer**
2.a Creating DSProxy
I tried to make a DS proxy and while the tx was mining I clicked the block native modal thinking this would show me the tx on etherscan. After re-routed and got hit by this image from ImToken:

![image](https://user-images.githubusercontent.com/12886084/86163930-42eeb600-bb11-11ea-9874-96adbb525565.png)

**Fix:** if possible, prevent the user from clicking on this or open it in a new tab. I know that obviously ImToken is hard to deal with here but was a bit janky after spending a lot on gas.

[Etherscan Tx](https://etherscan.io/tx/0x905af154240bcb8c17e5c6ae5c961b207556a4aa22947ccbbb1c69fc841fe54d)

**2.b Approving ImBTC**
Fortunately, the dapp recovered very well from crashing on the notifyjs tx bar. Approval went through fine. I thought I'd click the notifyjs bar again. This time it did not throw an error and actually loaded me to etherscan. HOWEVER it took me to a Kovan etherscan link.

**Fix** ensure that the notifyjs/onboardJs are both configured correctly and that it does not re-route to kovan.

[Etherscan Tx](https://etherscan.io/tx/0x2750d8e5e89cdfbb52b2761755d38a9e60ef0cf020d837a0a45cbd118a7d2056)

**2.c Create the sell offer**
I then went on to make 4 sell offers(see values in the table above). This was pretty smooth other than I came across a pretty small bug that if I removed all fields from the price input on the sell page (back space until empty) O could not type in `0.0xxx`. In other words I could not type in a leading zero followed by a `.`. Added to this I could put in invalid values here like `888...55..`. To Address this I had to reload the page.

**2.d Cancelling a cell offer**
This was pretty slick and mined fast. 
[Etherscan Tx](https://etherscan.io/tx/0x7edb1877985251ab83f0e27dfe9a3d5a9b124726ad963ab236472e87c340427e)

**3. Buying contracts**
I think that a relatively common activity will by the miner also going long. As a result, I used the same miner with DSProxy wallet to buy some contracts. Note that I did the **wallet 2** actions first so that I would not buy into my own limit order :)

**4. Redemption at expiry**
Redemption worked perfectly 3 days later (2 days for contract duration and 1 day for settlement delay).
[Etherscan Tx](https://etherscan.io/tx/0xc7a0812d0199567d222fe362f2ed3b56f9fd9d3ee23b955a3803f31eafbd2b94).

# Wallet 2: miner - Metamask on firefox. _No DSProxy_
- Address: 0xc9a0A08C4344b3dC015a5174453D244604a87152
- Sell Order1: 
	- Price: 0.0072
	- Quantity 150
For this user I wanted to buy IMBTC with USDC. This posed to be a bit of a problem as I wanted to swap a small amount (30 USDC) to imbtc and this is below the Tokenlon minimum limit! ALSO there are no dexes that let you trade imBTC. I cant trade it on uniswap, 1inch or Kyber. I'm limited to ONLY use Tokenlon. 

This raises a larger question on if we still want to use imBTC? I think wBTC is really the king of BTC on Ethereum right now, especially given it's in MCD. There is currently ~610 imBTC but there is ~8700 wBTC. This means that wBTC is far more liquidate and accessible. 

I was eventually able to make the sell order by getting imBTC ok Tokenlon.

**1. Approval ImBTC Tx Tx**
[Etherscan Tx](https://etherscan.io/tx/0x868085a4c86778b8335fbef41ff45e1a87f83e520618d3ca0aa9e5fc2b56e0fd)

**2. Redemption approval token tx short tokens**
[Etherscan Tx](https://etherscan.io/tx/0x375554eb6cef6b47fbe3819a5896e681decbdafc30672f57cee9a9988c785450)

POINT TO NOTE HERE: I was not told I needed to sign two transactions here. There should be the stepper modal like with creating the wallet that takes me through the approval steps.

**3. Redemption settlement tx**
[Etherscan Tx](https://etherscan.io/tx/0x58545f985d83beae088619047320f6a98d573ea62c9e55f2837fc8da96b1a075)

# Wallet 3: Buyer - Coinbase wallet on mobile. _No DSProxy_
- Address: 0x885F8b9d2E4df5bb39D2357342fE49cb139B4477
- Buy Order 1:
	- Quantity 324
	- Price 49.7078
	- Price 0.0767110
## Actions

I sent ether and USDT to coinbase wallet. I was, however, unable to approve the app to spend my USDT. After clicking the "skip" I clicked the approve button. The spinner loaded and then nothing. I was unable to sign the tx and so was blocked at this point. This issue was eventually solved by changing 
out the USDT interface contract. I was then able to do the buy order.

**1. Buying the tokens**
[Etherscan Tx](https://etherscan.io/tx/0x5c2b31e216d92d2445d65108fdb63eb1ec2f4291763e706cf70432b0ff818a01)

**Redeeming approval tx**
[Etherscan Tx](https://etherscan.io/tx/0x807118b9dad49d897a03f3a8fc81f90bc4f3e301670ad05bb0a287acf1dd967a)

**Redeeming redemption tx**
[Etherscan Tx](https://etherscan.io/tx/0x8fa21b357d2b5940d5f65b2844c3909c236d1003b2f252475ef87b32d05f7b71)

# Other issues

**1. Broken hyperlink**
The hyperlink in the menu to my wallet is wrong. 
![image](https://user-images.githubusercontent.com/12886084/86173671-9ddbd980-bb20-11ea-8746-3be43d23ab32.png)

After clicking the wallet address it takes me to this URL: https://main.etherscan.io/address/0x885f8b9d2e4df5bb39d2357342fe49cb139b4477

Clearly the `main.xxx` should not be in this URL.

**2. Cant edit input on buy side past zero**
I cant click backspace until the field is empty here. This means that I cant add a value as "10", for example, as I cant remove the two.
![image](https://user-images.githubusercontent.com/12886084/86173972-1d69a880-bb21-11ea-9db3-e821ab400e50.png)

It doesn't matter if I try move to the other side of the number or not I still can't delete this input.

**3. Wallet link does not work correctly**
Wallet link is like wallet connect, but for coinbase wallet. After failing to do the approval on coinbase wallet I through I'd try connecting the coinbase wallet directly to chrome via wallet link. The linking & QR code steps worked but I was unable to buy contracts as my wallet balance did not load correctly into the app. Screenshow below shows that my wallet is empty but this wallet has funds in it
![image](https://user-images.githubusercontent.com/12886084/86174398-d92ad800-bb21-11ea-971b-b51f02f2b1fa.png)

wallet [address](https://etherscan.io/address/0x885f8b9d2e4df5bb39d2357342fe49cb139b4477)

**Comment by FSM1** [comment]
Re 2a: It is opening in a new tab. that is how imtoken handles tabs.

2b - fixed
2c - the inputs are fragile. I will need to spend a good while fixing this. Will log a ticket.

other issues:
1. fixed
2. More input stuff. Will be resolved later...
3. Fixed (was using the wrong infura).
