### ISSUE TITLE
Incorrect value is displayed on the Buy>Budget screen

### ISSUE THREAD

**Issue by andrei-anisimov** [carboclan/dapp.honeylemon.market#46]
"You will pay X to buy..." - the X should be set to the `totalTakerFillAmount` returned from `getQuoteForBudget`. Currently it is set to the budget entered (you can validate that is not correct by multiplying the number of contracts by the price).
![image](https://user-images.githubusercontent.com/1471231/82164020-43820480-9863-11ea-9bf1-cbb40b742fd8.png)

**Comment by FSM1** [comment]
Resolved in #44
