### ISSUE TITLE
Separate miner and holder Portfolio screens

### ISSUE THREAD

**Issue by andrei-anisimov** [carboclan/dapp.honeylemon.market#47]
Currently both miner and holder use the same portfolio screen. We should separate those in order to have control over the UI elements: no New Offer button for holders, no offers table, etc. Since it is very rare that a user can be a miner and holder at the same time we can use two root-level routes to separate all the screens: `/miner`, `/holder`. So the routes would be:
```
/miner/offer
/miner/portfolio

/holder/buy
/holder/portfolio
```
We can essentially think of those two root-level routes as separate "apps" - it is likely in the future they might even leave on separate subdomains. There will be no cross-links between the "sides", once you choose a side all navigation will happen inside that side (e.g. miner or holder).

**Comment by andrei-anisimov** [comment]
@CarboClanC @chrismaree @scott-l-e-w-i-s  take a look at this one. We should settle on some final terminology for two "sides" in the protocol - this will govern the URLs among other things. One side is "Miner", but what about the other one? Investor? Buyer?

**Comment by chrismaree** [comment]
This is a great point @andrei-anisimov and I agree we should try to be as consistent with our nomenclature as possible. The routing you've got in your issue looks good to me.

If we re-named miner -> seller and investor -> buyer then the routing would be:
```
/miner/sell
/miner/portfolio

/holder/buy
/holder/portfolio
```

**Comment by FSM1** [comment]
An additional consideration for this is handling cases where the same user is on both sides of the transaction

**Comment by FSM1** [comment]
A decision has been made to keep the portfolio page universal in the current iteration.
