### ISSUE TITLE
UX Issues to resolve

### ISSUE THREAD

**Issue by FSM1** [carboclan/dapp.honeylemon.market#61]
This issue is used as a collection point for all UX feedback. Issues should be raised in the comments, with screenshots attached, as well as proposals on how to resolve.

**Comment by FSM1** [comment]
![image](https://user-images.githubusercontent.com/12774278/83062584-33d29f00-a05f-11ea-917e-c3ef38b3a324.png)

**Comment by chrismaree** [comment]
Issue: **CRITICAL**
I deployed a wallet contract but the UI did not update to show that I deployed this new contract. After reloading I got the same window saying "Deploy Wallet Contract"
![image](https://user-images.githubusercontent.com/12886084/83071650-c37f4a00-a06d-11ea-8fb4-30be04d76d46.png)
This means I cant get to the next page to actually buy contracts.

**Comment by chrismaree** [comment]
Issue: **High severity** 
404 on hard page re-load. This can be fixed in Netlify
![image](https://user-images.githubusercontent.com/12886084/83072261-bb73da00-a06e-11ea-9275-ab174bda0134.png)

See [here](https://stackoverflow.com/questions/58065603/netlify-renders-404-on-page-refresh-using-react-and-react-router) for a possible solution.

**Comment by chrismaree** [comment]
Issue: **Medium severity**
On the "Buy" page I can enter a budget and amount even before deploying smart contract wallet
![image](https://user-images.githubusercontent.com/12886084/83072399-fe35b200-a06e-11ea-8829-0acb3ce99aee.png)

This does not apply in the "offer" page.

**Comment by chrismaree** [comment]
Issue: **medium severity**
mining revenue index link does not work.
![image](https://user-images.githubusercontent.com/12886084/83072534-350bc800-a06f-11ea-8149-c388e3eee0cb.png)

This will require new text or a page to go to @CarboClanC

**Comment by FSM1** [comment]
more feedback from @CarboClanC 

![image](https://user-images.githubusercontent.com/12774278/83072747-9af84f80-a06f-11ea-91c2-be096c4b3073.png)

**Comment by chrismaree** [comment]
**Issue: text refinement**
This page is confusing to see what you got and what's happening. we need more text where to explain this section
![image](https://user-images.githubusercontent.com/12886084/83174637-f7fd0f80-a11a-11ea-998f-f0f48538eed5.png)

**Comment by chrismaree** [comment]
Portfolio withdrawal all button should be disabled if you don't have any positions
![image](https://user-images.githubusercontent.com/12886084/83174755-20850980-a11b-11ea-9c82-3bb020ff85af.png)

**Comment by chrismaree** [comment]
Deploy wallet contract button is not clear what it does. This should have a better description @talrasha007

**Comment by chrismaree** [comment]
There should be your wallet address and balance.

This can be in the menu bar or hidden in the burger.

This can also include a toggle switch for enabling approval of the different tokens.

**Comment by chrismaree** [comment]
More links to other pages. There needs to be a hyperlink to the github page, telegram community and other things of relevance.

**Comment by chrismaree** [comment]
Add validation messages to buy and sell. Right now there is no way to know why something didn't work and there should be a notification message.

There is something like this in the original design that we can include.

**Comment by chrismaree** [comment]
Remove leading zeros in input fields.

**Comment by chrismaree** [comment]
Link to FAQ page and docs on contract structure from the front end.

**Comment by chrismaree** [comment]
Comma separate thousands and number formatting.

**Comment by chrismaree** [comment]
Update links to all have underline and have different text.

**Comment by chrismaree** [comment]
Add loaders while contracts are mining. This can be a spinner until a transaction is mined.

**Comment by chrismaree** [comment]
Positions table should be hidden if there are no open positions.

**Comment by chrismaree** [comment]
If you don't have enough balance you should not ask for approval.

**Comment by FSM1** [comment]
* if incorrect network, if the network is changed the connect wallet button remains visible
* update graph to honeylemon.market graph for stats page
* Display balances and address in menu
* Deploy contract add spinner in control
* Add button like CSS to notification buttons
* Poller on portfolio page
* Spinner while loading on portfolio page
* contextual hiding of components on portfolio page
* Add "Open Orders" heading for Top section
* Remove "New Offer" From Portfolio Page
* Number formatting (thousands separator)

**Comment by jie85** [comment]
![image](https://user-images.githubusercontent.com/7948466/83320653-129aca00-a27c-11ea-872d-b0e9597d183c.png)
Next adjustment is always zero.

**Comment by jie85** [comment]
![image](https://user-images.githubusercontent.com/7948466/83321189-6a3b3480-a280-11ea-830d-0219c987cb17.png)
always loading after buying

**Comment by chrismaree** [comment]
Some more feedback from my most recent testing:

1. `Mining Revenue Index`  and See `full contract specification here` links still dont work
 
2. Filling an order should not proceed to the next page unless the tx has mined AND is showing in the UI. show a loading animation or whatever until it's processed.
 
3. Offer a contract should show you want the current market rate is. Right now it defaults in the field to the best market rate but it should also have some text saying that this is the current best market rate. A future point: if we could show the sell-side depth chart here that would be awesome.
 
4. Should not force the user to do an approval transaction every time. you should be able to pick to do bulk approve. A further point: You could add a toggle showing the accounts approve status in the menu next to the tokens Icon.
 
5. There are some additional fields the positions table should have like how many days have been spent in the duration of the contract. prehaps a loading bar or something to show this?

**Comment by chrismaree** [comment]
Some additional testing:
IMToken is still a bit broken, unfortunately. The deploy contract wallet and approval flow work correctly but if I'm making a sell offer as a miner then after signing the transaction the order does not load in the offers page. On the buy contracts page after re-directing from the buy sign transaction the positions loaded. After this, the short position I created loaded. Overall this means that the flow did work correctly but specifically after creating the sell offer it did not load immediately.

A few other points and feedback:
1) MRI & full contract spec buttons on buy pages still don't go anywhere. This needs more information.
2) The portfolio page positions should still need more info like the price. Prehaps a etherscan link to the tx would also be good. This can be taken from the positions object.
3) Collateral requirements on offer should have more decimal points. We take collateral unto the Satoshi so this should be shown. (8 decimal points)

**Comment by andrei-anisimov** [comment]
@FSM1  On the Offer screen the modal should say "Approve imBTC" instead of "Approve USDC". Also, a good idea to store token names in some central place to be able to easily change them.
![image](https://user-images.githubusercontent.com/1471231/83489425-3c621580-a463-11ea-9721-6a606751f53e.png)

**Comment by FSM1** [comment]
> Some additional testing:
> IMToken is still a bit broken, unfortunately. The deploy contract wallet and approval flow work correctly but if I'm making a sell offer as a miner then after signing the transaction the order does not load in the offers page. On the buy contracts page after re-directing from the buy sign transaction the positions loaded. After this, the short position I created loaded. Overall this means that the flow did work correctly but specifically after creating the sell offer it did not load immediately.
> 
> A few other points and feedback:
> 
> 1. MRI & full contract spec buttons on buy pages still don't go anywhere. This needs more information.
> 2. The portfolio page positions should still need more info like the price. Prehaps a etherscan link to the tx would also be good. This can be taken from the positions object.
> 3. Collateral requirements on offer should have more decimal points. We take collateral unto the Satoshi so this should be shown. (8 decimal points)

This is being handled in #96
