### ISSUE TITLE
Optimize website network transfer

### ISSUE THREAD

**Issue by chrismaree** [carboclan/dapp.honeylemon.market#62]
right now the network transfers a lot of traffic. A lot of network transfer occurs right now:

![image](https://user-images.githubusercontent.com/12886084/83067488-0b4ea300-a067-11ea-8d65-33ff22d39666.png)

this is way too much and the build needs to be optimized.

**Comment by FSM1** [comment]
![image](https://user-images.githubusercontent.com/12774278/83195526-a4022300-a13a-11ea-8f61-6c11c0af2611.png)
![image](https://user-images.githubusercontent.com/12774278/83195540-a9f80400-a13a-11ea-92b2-ad667f44f619.png)

Build optimization results
