### ISSUE TITLE
Add disclaimer to website 

### ISSUE THREAD

**Issue by chrismaree** [carboclan/dapp.honeylemon.market#64]
We should make it clear that we are an Alpha product and there is risk!

**Comment by FSM1** [comment]
We need some proposals for methods of notifying users. A splash screen on the home page?

**Comment by FSM1** [comment]
See disclaimer above connect button: 
![image](https://user-images.githubusercontent.com/12774278/88468265-362b6b00-cee1-11ea-93c3-9de3ea67a096.png)
