### ISSUE TITLE
Add down for maintenance if no new daily contract has been deployed

### ISSUE THREAD

**Issue by chrismaree** [carboclan/dapp.honeylemon.market#85]
In the event that a new contract has not been deployed the front end should say "down for maintenance"

**Comment by FSM1** [comment]
Is there a way we can check this before the user connecting their wallet (instantiating the service)? Also, which call would I need to make to get the last contract deployed time? @andrei-anisimov @chrismaree I remember you mentioning something about this yesterday.

**Comment by FSM1** [comment]
This is also a duplicate of #63

**Comment by FSM1** [comment]
Resolved in #125
