### ISSUE TITLE
Links to SM collateral

### ISSUE THREAD

**Issue by FSM1** [carboclan/dapp.honeylemon.market#86]
More links to other pages. There needs to be a hyperlink to the github page, telegram community and other things of relevance.

_Originally posted by @chrismaree in https://github.com/carboclan/dapp.honeylemon.market/issues/61#issuecomment-635535892_

**Comment by FSM1** [comment]
Proposal here to include these in a floating footer. @CarboClanC @andrei-anisimov @chrismaree what are the thoughts on this. Just a series of icons for the various collateral links

**Comment by FSM1** [comment]
Will be using this component for the footer: https://components-extra.netlify.app/components/footer

**Comment by CarboClanC** [comment]
> More links to other pages. There needs to be a hyperlink to the github page, telegram community and other things of relevance.
> 
> _Originally posted by @chrismaree in [#61 (comment)](https://github.com/carboclan/dapp.honeylemon.market/issues/61#issuecomment-635535892)_

Link to Github:
https://github.com/carboclan/dapp.honeylemon.market

Link to Whitepaper:
https://github.com/carboclan/pm/blob/master/research/Honeylemon/HoneyLemonWhitepaper.md

Link to Telegram:
https://t.me/joinchat/I9o0JBU3JKkxb-yRSkIFvA
