### ISSUE TITLE
IMToken 0x bug

### ISSUE THREAD

**Issue by chrismaree** [carboclan/dapp.honeylemon.market#96]
Creating an offer as a miner in IMToken has a bug after signing the sell order. The deploy contract wallet and approval flow work correctly but if I'm making a sell offer as a miner then after signing the transaction the order does not load in the offers page. 

On the buy contracts page after re-directing from the buy sign transaction the positions loaded. After this, the short position I created loaded. Overall this means that the flow did work correctly but specifically after creating the sell offer it did not load immediately.

**Comment by outprog** [comment]
@chrismaree ch Did you use websocket load data from ethereum node?
imToken eth node not support websocket now.

**Comment by andrei-anisimov** [comment]
@FSM1 are we using websockets in this scenario?

**Comment by FSM1** [comment]
I would need to check that.

**Comment by outprog** [comment]
@sapjax cc.
Dapp for imBTC use our imToken browser

**Comment by FSM1** [comment]
Closed in #61
