### ISSUE TITLE
Warn the user if their transaction is too small and they will loose with gas price

### ISSUE THREAD

**Issue by chrismaree** [carboclan/dapp.honeylemon.market#97]
If the user is making a small buy (less than 20 USD say) they should be told they are going to spend most on their gas.

**Comment by FSM1** [comment]
@chrismaree @CarboClanC @andrei-anisimov can we settle on a threshold value at which the message will be hidden, as well as what the copy of the message should say?

**Comment by FSM1** [comment]
closed in #169
